config/routes.rb
Rails.application.routes.draw do

  devise_for :admin,skip:[:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }

  # /admin/dashboardsにアクセスするとadmin/dashboards_controller.rbのindexアクションを処理
  namespace :admin do
    get 'dashboards', to: 'dashboards#index'
    resources :users, only: [:destroy]
  end
  
  scope module: :public do
    devise_for :users
    root 'homes#top'
    get 'homes/about' => 'homes#about' , as: 'about'

    # コントローラの同じ名前のアクションに紐づく形で、ルーティングを自動生成
    resources :post_images, only: [:new, :create, :index, :show, :destroy] do
      # このような親子関係を、「ネストする」と言うネストしたURLを作成することでparams[:post_image_id]でPostImageのidが取得できる

      # 今まではresourcesでしたが、ここでは、resource 単数形にすると、/:idがURLに含まれなくなります。
      resource :favorite, only: [:create, :destroy]
      # ルーティングpost_image_post_comments
      resources :post_comments, only: [:create, :destroy]
    end

    resources :users, only: [:show, :edit , :update]
  end

  


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post_image.rb
class PostImage < ApplicationRecord

  has_one_attached :image

  # belongs_to    アソシエーション
  belongs_to :user
  # has_many アソシエーション　dependent: :destroy 1:Nの1側が削除されたとき、N側を全て削除する
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  
  # shop_nameが存在しているかを確認するバリデーション　trueと記述すると、データが存在しなければならないという設定
  validates :shop_name, presence: true
  
  # imageが存在しているかを確認するバリデーション
  validates :image, presence: true
  

  # 投稿画像表示用のメソッド
  def get_image
    # unless ifと逆
    unless image.attached?
      # `Rails.root.join`は、Railsアプリケーションでファイルパスを生成するためのメソッド
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg',content_type: 'image/jpeg' )
    end
    image
  end


  # favorited_by?メソッドを作成
  # 引数で渡されたユーザidがFavoritesテーブル内に存在（exists?）するかどうかを調べる。 存在していればtrue、存在していなければfalse
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
  def new
    @post_image =PostImage.new
  end

  def create
    @post_image =PostImage.new(post_image_params)
    # @post_image.user_id,この投稿の user_id としてcurrent_user.id の値を代入する
    # current_user→ deviseヘルパーメソッド　current_user.id と記述することでログインユーザーの id を取得する
    @post_image.user_id = current_user.id
    if @post_image.save
      redirect_to post_images_path
    else
      render :new
    end
  end


  def index
    # pageメソッドは、kaminariをインストールしたことで使用できる
    @post_images = PostImage.page(params[:page])

  end
  def show
    @post_image = PostImage.find(params[:id])
    @post_comment = PostComment.new
  end

  def destroy
    post_image = PostImage.find(params[:id])
    post_image.destroy
    redirect_to post_images_path
  end

  # ストロングパラメータ
  private

  def post_image_params
    params.require(:post_image).permit(:shop_name, :image, :caption)
  end

end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/views/post_images/_list.html.erb
<div class="card-list-container py-5">
  <% post_images.each do |post_image| %>
    <%# "card"：Bootstrapのカード（Card）スタイルを適用するためのクラス %>
    <%# "w-50"：幅（Width）を50%に設定するためのクラスです。要素の幅が親要素の50% %>
    <%# "mx-auto"：左右のマージン（Margin）を自動で設定するためのクラスです。要素を水平方向に中央揃え %>
    <%# "mt-4"：上部のマージン（Margin） %>
    <%# "shadow-lg"：要素に大きな影を付けるためのクラス  "lg"は影の大きさ  　大きい影%>
    <div class="card w-50 mx-auto mt-4 shadow-lg">
      <%= link_to post_image_path(post_image.id) do %>
        <%# "card-img-top"：Bootstrapのカード（Card）コンポーネント内で、画像をカードの上部に配置するためのクラス %>
        <%= image_tag post_image.get_image, class: "card-img-top"; %>
      <% end %>
      <%# "card-body"：Bootstrapのカード内で、テキストやボタンなどの本文やコンテンツを配置するコンテナを示すクラス %>
      <div class="card-body">
        <div class="row">
          <div class="col-2">
            <%# post_image.userで、投稿画像に紐づいたユーザーの情報(投稿したユーザーの情報)を取得できる %>
            <%# Userモデルに記述しているget_profile_imageメソッドが使える %>
            <%#  "mt-3 : margin-top:3の意味    "rounded-circle"：要素を角丸の円形（丸型）にするためのクラス　 %>
            <%= image_tag post_image.user.get_profile_image(100,100), class: "mt-3 rounded-circle"; %>
          </div>
          <div class="col-10">
            <%# "class="card-title"は、Bootstrapのカード（Card）コンポーネント内でタイトルを表示するためのクラス %>
            <p class="card-title">
              <%# 'text-dark'"は、テキストの色を暗くするためのクラス %>
              <%= link_to(post_image_path(post_image.id), class: "text-dark") do %>
                <%# "far fa-flag"はFontAwesomeのクラス名で、"fa-flag"は旗のアイコンを表し、"fa-2x"などのクラスを追加することでサイズを変えられる %>
                <strong><i class="far fa-flag"></i><span> <%= post_image.shop_name %></span></strong>
              <% end %>
            </p>
            <%# "card-text"は、Bootstrapのカード（Card）コンポーネント内で本文やテキストを配置するためのクラス %>
            <p class="card-text">説明：<%= post_image.caption %></p>
            <%# "fas fa-user"は、FontAwesomeアイコンセットの中からユーザー（User）アイコンを表示するためのクラス %>
            <span><i class="fas fa-user"></i> By <%= post_image.user.name %> ｜ </span>
            <span><%= link_to "#{post_image.post_comments.count} コメント", post_image_path(post_image.id), class: "text-dark" %></span>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <%= paginate post_images %>
</div>

app/views/post_images/index.html.erb
<!--PostImages#index-->
<!--投稿一覧画面-->

<!--<render [部分テンプレートファイルの指定], [ローカル変数]:[渡す値] -->
<!--拡張子は省略でき、同じフォルダ内から呼び出す場合はフォルダ名も省略できる-->
<%= render 'list', post_images: @post_images %>

app/views/post_images/new.html.erb
<!--PostImages#new-->

<div class="container">
  <%#  "no-gutters"：行（Row）内の列（Column）間に余白（Gutters）を設定しないことを示すクラス %>
  <div class="row no-gutters">
    <%# "col-md-5"：中サイズ（Medium）の画面以上（viewport width>=768px）では、5つの列の幅を持つコンテンツとして表示 %>
    <%#  "col-sm-10"：小サイズ（Small）の画面以上（viewport width>=576px）では、10つの列の幅を持つコンテンツとして表示 %>
    <%#  "mx-2"：水平方向（左右）の余白として2のスペースを設定 %>
    <%#  "mx-sm-auto"：小サイズ以上の画面において、水平方向の余白を自動的に設定 %>
    <%# "shadow-lg"：コンテンツに大きな影を付けるためのクラス %>
    <%#  "rounded"：コンテンツを角丸にするためのクラス %>
    <%# "px-0"：左右のパディング（Padding）を0に設定   "my-5"：上下のマージン（Margin）として5のスペースを設定 %>
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <%# "text-dark"：テキストのカラーを暗く（通常は黒色）に設定するためのクラス %>
      <%# "bg-light"：背景色を明るい色（通常は白色）に設定するためのクラス %>
      <%# "p-4"：上下左右にパディング（余白）を4つ分追加するためのクラス "mb-0"：下部のマージン（余白）を0に設定するためのクラス %>
      <h5 class="text-dark bg-light p-4 mb-0">画像投稿フォーム</h5>
      <%#  "form-body"：フォーム内の本文やコンテンツを格納するためのクラス   "p-4"：パディング（余白）を4つ分追加するためのクラス %>
      <div class="form-body p-4">
        <%# errors.any? エラーが発生しているか？ %>
        <% if @post_image.errors.any? %>
          <%#  "alert alert-danger"：Bootstrapのアラート（alert）コンポーネントを赤色の危険タイプ（Danger）に設定するためのクラス %>
          <%#  "role="alert""：この属性は、スクリーンリーダーなどの支援技術が意味的に正しい方法でアラートを処理できるようにするためのもの %>
          <ul class="alert alert-danger" role="alert">
            <%# "alert-heading""：アラートコンポーネント内で重要な見出し（Heading）に適用されるクラス %>
            <h6 class="alert-heading">
              <%# errors.count エラーの数をカウント %>
              <%= @post_image.errors.count %>件のエラーが発生しました
            </h6>
            <%# errors.full_messages エラーの内容を出力 %>
            <% @post_image.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
        <%= form_with model: @post_image do |f| %>
          <%# :image"：フォームフィールドの名前（パラメーター名） %>
          <%# "accept: "image/*""：アップロードできるファイルの種類を画像ファイルに制限 %>
          <%# "w-100""：フォームフィールドに幅100%を設定するBootstrapのクラス %>
          <%= f.file_field :image, accept: "image/*", class: "w-100" %>
          <%# "input-group"：Bootstrapのクラスで、入力フィールドやボタンなどのコンポーネントをまとめるためのグループ化クラス %>
          <%# "mb-3"：下部（Bottom）マージン（余白）を3のスペース分設定するためのクラス "mt-4"：上部（Top）マージン（余白）を4のスペース分設定するためのクラス %>
          <div class="input-group mb-3 mt-4">
            <%#  "input-group-prepend"：Bootstrapのクラスで、入力グループ内の要素が前に配置されることを示すクラスです。 %>
            <%# このクラスを使用すると、入力フィールドやボタンなどの前に配置される要素にスタイリングを適用することができる %>
            <div class="input-group-prepend">
              <%# "input-group-text"は、Bootstrapの入力グループ（Input Group）で使用されるクラスで、フォームコントロール要素の前に配置されるテキストや要素を装飾するためのクラス %>
              <%# "aria-hidden="true""は、アクセシビリティ（Accessibility）の観点から、画面上で表示されるがスクリーンリーダーなどの支援技術には非表示として示すための属性 %>
              <%# "aria-hidden"属性に"true"を設定することで、その要素がスクリーンリーダーに非表示として扱われ、読み上げや操作の対象外となります %>
              <%# class="fas fa-building"：FontAwesomeの"fa-building"アイコンを表示するための要素 "fas"はSolidアイコンスタイルを指定し、"fa-building"は建物アイコンを意味します。%>
              <span class="input-group-text" aria-hidden="true"><i class="fas fa-building"></i></span>
            </div>
            <%# ":shop_name"：フォームフィールドの名前（パラメーター名） %>
            <%# "class: "form-control""：フォームフィールドにBootstrapのスタイルを適用するためのクラス。「form-control」クラスは、Bootstrapのスタイルを適用してフォームフィールドを整形 %>
            <%# "placeholder: "ショップ名""：フォームフィールドにプレースホルダーとして表示されるテキストを指定。ユーザーが入力するべき内容を示すためのヒントとして表示される %>
            <%= f.text_field :shop_name, class: "form-control", placeholder: "ショップ名" %>
          </div>
          <%#  "rows: "3""：テキストエリアの表示行数を3行に設定するオプション。これにより、最初から3行の高さが表示される %>
          <%= f.text_area :caption, class: "form-control", rows: "3", placeholder: "コメントここに" %>
          <hr>
          <%# "btn"：Bootstrapのボタンスタイルを適用するためのクラス %>
          <%# "btn-lg"：大きなサイズのボタンを示すクラス %>
          <%# "btn-block"：ボタンを幅いっぱいに広げるためのクラス %>
          <%# "btn-info"：情報を表す青色のボタンスタイルを適用するクラス %>
          <%# "mt-4"：上部（Top）マージン（余白）を4のスペース分設定するためのクラス %>
          <%= f.submit '投稿', class: "btn btn-lg btn-block btn-info mt-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/post_images/show.html.erb
<!--PostImages#show-->
<!--投稿詳細画面-->

<!--投稿詳細-->
<div>
  <%= image_tag @post_image.get_image %>
  <p>ショップ名：<%= @post_image.shop_name %></p>
  <p>説明：<%= @post_image.caption %></p>
  <p>投稿ユーザー画像：<%= image_tag 'sample-author1.jpg' %></p>
  <p>ユーザーネーム：<%= @post_image.user.name %></p>
  <p>投稿日：<%= @post_image.created_at.strftime('%Y/%m/%d') %></p>
  <!--現在ログインしているユーザ だったら-->
  <% if @post_image.user == current_user %>
    <%= link_to "削除", post_image_path(@post_image), method: :delete %>
  <% end %>

  <!--いいね機能-->
  <!--favorited_by? post_image.rbで定義したメソッド。idがFavoritesテーブル内に存在（exists?）するかどうかを調べる-->
  <% if @post_image.favorited_by?(current_user) %>
  　<!--存在しているときTrue-->
    <p>
      <%= link_to post_image_favorite_path(@post_image), method: :delete do %>
        ♥<%= @post_image.favorites.count %> いいね
      <% end %>
    </p>

  <% else %>
    <!--存在していない時false  -->
    <p>
      <%= link_to post_image_favorite_path(@post_image), method: :post do %>
        ♡<%= @post_image.favorites.count %> いいね
      <% end %>
    </p>
  <% end %>
</div>

<!--コメント-->
<div>
  <p>コメント件数：<%= @post_image.post_comments.count %></p>
  <% @post_image.post_comments.each do |post_comment| %>
    <p><%= image_tag post_comment.user.get_profile_image(100,100) %></p>
    <%= post_comment.user.name %>
    <%= post_comment.created_at.strftime('%Y/%m/%d') %><%= post_comment.comment %>
    <!--現在ログインしているユーザ だったら-->
    <% if post_comment.user == current_user %>
      <%= link_to "削除", post_image_post_comment_path(post_comment.post_image, post_comment), method: :delete %>
    <% end %>
  <% end %>
</div>
<div>
  <!--インスタンス変数を2つ指定している。コメントは、post_imageに結びついたpost_commentであるため、2つ用意する必要がある-->
  <%= form_with model: [@post_image, @post_comment] do |f| %>
    <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
    <%= f.submit "送信する" %>
  <% end %>
</div>